version: "3.1"


services:


  db_produtos_api:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    expose:
      - "5435"
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin