spring:
  datasource:
    url: ${URL_POSTGRES}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
       ddl_auto: update

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:user}
    password: ${RABBITMQ_DEFAULT_PASS:123456}
    virtual-host: /