version: "3.1"


services:

  produtos_api:
    container_name: produto-api
    image: produto-api:v1
    restart: always
    ports:
      - "8080:8080"
    environment:
      - URL_POSTGRES=jdbc:postgresql://db_produtos_api:5432/product
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=docker
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_HOST=rabbitmq
    depends_on:
      - db_produtos_api
      - rabbitmq

  db_produtos_api:
    container_name: db_produtos_api

    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmqData:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456

  producer:
    container_name: producer
    image: producer:v1
    restart: always
    ports:
      - "8081:8080"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - PRODUTO_API_URL=produto-api
      - PRODUTO_API_PORT=8080
    depends_on:
      - produtos_api
      - rabbitmq
