spring:
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:user}
    password: ${RABBITMQ_DEFAULT_PASS:123456}
    virtual-host: /

url:
  produto-api: ${PRODUTO_API_URL:localhost}
  port: ${PRODUTO_API_PORT:8080}

