spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5435/product
    username: postgres
    password: admin
  flyway:
#    url: ${spring.datasource.url}
#    username: ${spring.datasource.username}
#    password: ${spring.datasource.password}
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true