spring:
  profiles: local
  flyway:
    url: jdbc:h2:mem:~/products
    user: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/products
    username: sa
    password:
    driverClassName: org.h2.Driver